[dev]
  command = "cameronjs dev"
  publish = "publish"
  port = 8080

[build]
  command = "yarn build"
  publish = "publish"
  functions = "functions"

# For more settings see https://www.netlify.com/docs/netlify-toml-reference/#post-processing
[build.processing]
  skip_processing = false
[build.processing.css]
  minify = true
[build.processing.js]
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[context.production]
  environment = { NODE_ENV = "production"}

[context.branch-deploy]
  environment = { NODE_ENV = "production" }

[[redirects]]
  from = "/guides"
  to = "/guides/introduction"
  status = 301
  force = true
  headers = {Turbolinks-Redirect = '/guides/introduction'}

[[redirects]]
  from = "/tutorial"
  to = "/tutorial/welcome-to-redwood"
  status = 301
  force = true
  headers = {Turbolinks-Redirect = '/tutorial/welcome-to-redwood'}

[[redirects]]
  from = "/cookbook"
  to = "/cookbook/disable-api-database"
  status = 301
  force = true
  headers = {Turbolinks-Redirect = '/cookbook/disable-api-database'}

[[redirects]]
  from = "/reference"
  to = "/reference/redwood-form"
  status = 301
  force = true
  headers = {Turbolinks-Redirect = '/reference/redwood-form'}

[[redirects]]
  from = "/home"
  to = "/"
  status = 301
  force = true
  headers = {Turbolinks-Redirect = '/'}

# See https://www.netlify.com/docs/netlify-toml-reference/#headers
[[headers]]
