[dev]
  command = "cameronjs dev"
  publish = "publish"
  port = 8080

[build]
  command = "yarn build"
  publish = "publish"
  functions = "functions"

# For more settings see https://www.netlify.com/docs/netlify-toml-reference/#post-processing
[build.processing]
  skip_processing = false
[build.processing.css]
  minify = true
[build.processing.js]
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[context.production]
  environment = { NODE_ENV = "production"}

[context.branch-deploy]
  environment = { NODE_ENV = "production" }

[[redirects]]
  from = "/tutorial"
  to = "/tutorial/welcome-to-redwood.html"
  status = 301

[[redirects]]
  from = "/docs"
  to = "/docs/introduction.html"
  status = 301

[[redirects]]
  from = "/cookbook"
  to = "/cookbook/using-a-third-party-api.html"
  status = 301

[[redirects]]
  from = "/home"
  to = "/"
  status = 301

# See https://www.netlify.com/docs/netlify-toml-reference/#headers
[[headers]]
